-- Seed the faqs table with the original 33 hardcoded FAQs from the
-- pre-CMS faqs.php, and remove two legacy rows that predated the CMS.
--
-- Run once after `scripts/faqs-schema.sql` (or after the manual ALTER
-- TABLE that adds the `category` column on older MySQL).
--
-- Not idempotent — running twice will insert duplicates. If you need
-- to re-seed, TRUNCATE the table first.

DELETE FROM faqs WHERE id IN (1, 3);

INSERT INTO faqs (question, answer, category, published) VALUES
('How do I get started with BELTRALACE?',
 'Click "Get Started" on our homepage and fill in the enquiry form. Tell us which language you want to learn and your current level. Our team will respond within 24 hours to match you with the right trainer and schedule your first lesson.',
 'Getting Started', 1),
('Do you offer a free trial lesson?',
 'Yes! New students get a FREE 30-minute taster lesson to meet their trainer and experience our teaching style before committing to a full programme. No payment is required. Simply click "Book Free Taster" on our homepage.',
 'Getting Started', 1),
('How quickly can I start lessons?',
 'In most cases you can start within 24–48 hours of enquiring. Once you submit the form, our team will contact you to confirm your trainer, schedule and first lesson date.',
 'Getting Started', 1),
('Do I need to create an account?',
 'No account creation is needed to enquire. Simply fill in our contact form and our team will take care of everything from there — trainer matching, scheduling, and onboarding.',
 'Getting Started', 1),

('How are lessons delivered?',
 'All lessons are delivered online via video conferencing platforms such as Zoom, Google Meet, or Skype. This means you can learn from anywhere in the world at a time that suits you — no travel required.',
 'Lessons & Delivery', 1),
('Do you offer face-to-face lessons?',
 'Yes — face-to-face lessons are available for students based in Nairobi, Kenya. Our private lesson package table on the Pricing page shows both virtual (worldwide) and face-to-face (Nairobi) rates.',
 'Lessons & Delivery', 1),
('What is the difference between group, semi-private, and private lessons?',
 'Private lessons ($40/hr) are one-on-one with a trainer, fully tailored to your pace and goals. Semi-private lessons ($10/hr per student) are for 2–4 students sharing a session. Group lessons ($8/hr per student) are for 5 or more students. Group lessons are more affordable; private lessons offer maximum personalisation.',
 'Lessons & Delivery', 1),
('How long is each lesson?',
 'Standard lessons are 60 minutes. Crash course sessions can run up to 90 minutes for students who wish to cover more content in less time. Lesson duration can be discussed with your trainer during onboarding.',
 'Lessons & Delivery', 1),
('Do you offer weekend lessons?',
 'Yes — we offer lessons 7 days a week including weekends. Our online format means you can book a lesson at any time that fits your schedule, whether early morning or evening.',
 'Lessons & Delivery', 1),
('What if I miss a lesson?',
 'Life happens — we understand. If you need to cancel or reschedule, please notify us at least 24 hours in advance and we will rearrange your lesson at no extra cost. Late cancellations may be charged at the trainer''s discretion.',
 'Lessons & Delivery', 1),
('Do you provide lesson materials?',
 'Yes — your trainer will provide lesson materials, exercises, vocabulary lists, and resources tailored to your level and goals. Materials are typically shared digitally before or during the lesson.',
 'Lessons & Delivery', 1),
('Can I record my lessons?',
 'You may record lessons for personal study purposes with your trainer''s consent. We recommend discussing this with your trainer at the start of your programme.',
 'Lessons & Delivery', 1),

('What languages do you teach?',
 'We offer lessons in over 100 languages including Swahili, English, French, Spanish, German, Portuguese, Italian, Mandarin Chinese, Arabic, Japanese, Korean, Russian, Hindi, Dutch, and many more. Contact us if you don''t see your language listed — we will do our best to find you a suitable trainer.',
 'Languages & Trainers', 1),
('Are all your trainers native speakers?',
 'Yes — 100% of our trainers are native speakers of the language they teach. This ensures you learn authentic pronunciation, natural expressions, and real cultural context from your very first lesson. All trainers are also qualified and experienced language educators.',
 'Languages & Trainers', 1),
('Can I switch trainers if I am not happy?',
 'Absolutely. Student satisfaction is our priority. If you feel your trainer is not the right fit — whether in terms of teaching style, pace, or personality — simply contact us and we will match you with another trainer at no extra cost.',
 'Languages & Trainers', 1),
('Can I learn multiple languages at the same time?',
 'Yes — many of our students learn two or even three languages simultaneously. We recommend spacing lessons on different days to avoid confusion between languages. Our team can help you build an effective multi-language schedule.',
 'Languages & Trainers', 1),
('Can I learn a language for a specific purpose?',
 'Absolutely — we specialise in purpose-driven learning: business language, travel preparation, exam preparation (DELF, DALF, Goethe, HSK), family connections, missionary and NGO work, and academic purposes. Tell us your goal and we will build a programme tailored around it.',
 'Languages & Trainers', 1),
('What is the minimum age for lessons?',
 'We offer language lessons for learners of all ages — from young children to adults and seniors. Our trainers are experienced in adapting their teaching style to suit the learner''s age and level. Contact us to discuss a suitable programme for your child.',
 'Languages & Trainers', 1),
('How long does it take to learn a new language?',
 'It depends on the language, your starting level, and how much time you practise. With consistent daily effort, most students can hold basic conversations within 3 months. Our native-speaking trainers will set realistic milestones based on your specific goals.',
 'Languages & Trainers', 1),

('How much do lessons cost?',
 'Our rates are: Group lessons (5+ students) — $8/hr per student. Semi-private (2–4 students) — $10/hr per student. Private lessons — $40/hr. Crash course — $55/hr. Private package rates vary by hours committed — see our full pricing table on the <a href="/pricing" style="color:#4db8e8;">Pricing page</a>.',
 'Pricing & Packages', 1),
('What are the Swahili language packages?',
 'We offer three fixed-price Swahili programs: Beginner (4 weeks, KSh 25,000) — build core conversational skills. Intermediate Boot Camp (6 weeks, KSh 35,000) — gain real-world fluency. Advanced Crash Program (10 weeks, KSh 55,000) — master advanced grammar and professional Swahili. All packages have a fixed price — no per-lesson billing.',
 'Pricing & Packages', 1),
('Do you offer group discounts?',
 'Yes — group and semi-private lessons are already discounted compared to private rates. For corporate groups of 5 or more, contact us for a custom package quote. We regularly work with NGOs, businesses, and organisations on tailored group programmes.',
 'Pricing & Packages', 1),
('How do I pay?',
 'We accept M-Pesa, bank transfer (Kenya and international), and other payment methods depending on your location. Contact us when enrolling and our team will advise on the most convenient payment option for you.',
 'Pricing & Packages', 1),
('Is there a refund policy?',
 'We offer a satisfaction guarantee. If you are not happy after your first paid lesson, contact us and we will do our best to resolve the issue — either by reassigning your trainer or discussing a suitable arrangement. Please contact us within 7 days of your first lesson.',
 'Pricing & Packages', 1),
('Do you offer corporate language training?',
 'Yes — we offer corporate language training packages tailored for businesses, NGOs, government agencies, and organisations. We have previously provided training for Helen Keller International and Smart HealthCare Solution among others. Contact us for a corporate quote.',
 'Pricing & Packages', 1),

('Do you offer translation services?',
 'Yes — we offer certified translation and interpretation services across many language pairs. We have translated documents for Helen Keller International, Smart HealthCare Solution, and collaborated with OJ Language Hub on various translation projects. Contact us with your document and language pair for a quote.',
 'Translation Services', 1),
('What types of translation do you offer?',
 'We offer document translation, community service document translation, legal translation, business translation, interpretation (simultaneous and consecutive), subtitling, transcription, and voice-over services. Contact us to discuss your specific requirements.',
 'Translation Services', 1),
('How do I get a translation quote?',
 'Contact us via email at info@beltralace.com or through our contact form. Share the document you need translated, the source and target languages, and your deadline. We will get back to you with a quote within 24 hours.',
 'Translation Services', 1),
('Are your translations certified?',
 'Yes — BELTRALACE is a registered member of Proz.com (the world''s leading professional translation platform) and the East Africa Interpreters and Translators Association (EAITA). Our translations are carried out by qualified professional linguists.',
 'Translation Services', 1),

('Is BELTRALACE a registered professional organisation?',
 'Yes. BELTRALACE (Belxin Translators and Language Centre) is a registered member of Proz.com and the East Africa Interpreters and Translators Association (EAITA). We have operated professionally since 2012.',
 'About BELTRALACE', 1),
('Where is BELTRALACE based?',
 'BELTRALACE is based in Nairobi, Kenya, but operates as an online language school serving students worldwide. Face-to-face lessons are available for students in Nairobi.',
 'About BELTRALACE', 1),
('How do I become a language trainer at BELTRALACE?',
 'We are always looking for qualified native-speaking language trainers. Visit our <a href="/teaching-jobs" style="color:#4db8e8;">Teaching Jobs page</a> to submit your application with your CV, cover letter, and passport photo.',
 'About BELTRALACE', 1),
('How can I contact BELTRALACE?',
 'You can reach us by email at info@beltralace.com, by phone at +254 724 736 255, via WhatsApp at the same number, or through our <a href="/contact-us" style="color:#4db8e8;">Contact page</a>. We typically respond within 24 hours.',
 'About BELTRALACE', 1);
